"""Captures real /api/run and /api/verify responses into demo/replay.js.

The demo page calls the live TARA API when one is reachable. When it is not —
a cold host, no network at the venue, or a viewer who opens the page before
the service is deployed — it falls back to these captured responses and says
so in the header, rather than showing nothing or, worse, inventing something.

Everything in the generated file is real output from the real pipeline. This
script only moves it; it never composes a result.

Re-run after any change to a domain pack, the register schema, or the agents:

    python -m uvicorn demo.api:app --port 8000 &
    python demo/capture_replay.py
"""
from __future__ import annotations

import itertools
import json
import urllib.request
from datetime import date
from pathlib import Path

BASE = "http://127.0.0.1:8000"
DEMO = Path(__file__).resolve().parent
AS_OF = date.today().isoformat()

def post(path: str, body: dict) -> dict:
    req = urllib.request.Request(
        BASE + path, data=json.dumps(body).encode(),
        headers={"content-type": "application/json"},
    )
    return json.loads(urllib.request.urlopen(req).read())


def jsnum(v: object) -> str:
    """Render a value the way JavaScript's String() would, so a key built in
    Python matches the same key built in the browser."""
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, float) and v == int(v) and abs(v) < 1e21:
        return str(int(v))
    if v is None:
        return "null"
    return str(v)


def artefact_key(preset: str, action_id: str, artefact: dict) -> str:
    body = ";".join(f"{k}={jsnum(v)}" for k, v in sorted(artefact.items()))
    return f"{preset}::{action_id}::{body}"


def answers_key(preset: str, answers: dict) -> str:
    return preset + "::" + ";".join(f"{k}={jsnum(v)}" for k, v in sorted(answers.items()))


def main() -> None:
    presets = json.loads((DEMO / "presets.json").read_text(encoding="utf-8"))
    runs: dict[str, dict] = {}
    verifies: dict[str, dict] = {}
    open_band: dict | None = None

    for preset in presets:
        pid = preset["id"]
        base = {"holder": preset["holder"], "holdings": preset["holdings"], "as_of": AS_OF}

        # Discover the interview questions this profile reaches, then capture
        # every combination of answers to them; the loop does not assume a
        # fixed question or profile count.
        probe = post("/api/run", {**base, "answers": {}})
        qids = [q["question_id"] for q in probe["pending_questions"]]
        combos: list[dict] = [{}]
        for r in range(1, len(qids) + 1):
            for subset in itertools.combinations(qids, r):
                for values in itertools.product([False, True], repeat=r):
                    combos.append(dict(zip(subset, values)))

        for answers in combos:
            run = post("/api/run", {**base, "answers": answers})
            if open_band is None:
                open_band = run["open_band"]
            # The OPEN band is byte-identical across every run by design — it
            # is computed once and serves everyone. Store it once.
            assert run["open_band"].keys() == open_band.keys()
            run.pop("open_band")
            runs[answers_key(pid, answers)] = run

            for action in run["actions"]:
                # The server builds every variant, so a replayed submission is
                # byte-identical to the live one it stands in for.
                for variant in action.get("variants", {}).values():
                    artefact = variant["artefact"]
                    key = artefact_key(pid, action["action_id"], artefact)
                    if key in verifies:
                        continue
                    verifies[key] = post("/api/verify", {
                        **base, "answers": answers,
                        "domain_id": action["domain_id"],
                        "action_id": action["action_id"],
                        "artefact": artefact,
                    })

    payload = {
        "captured_at": AS_OF,
        "as_of": AS_OF,
        "open_band": open_band,
        "runs": runs,
        "verifies": verifies,
    }
    out = DEMO / "replay.js"
    out.write_text(
        "/* Generated by demo/capture_replay.py — real pipeline output, captured "
        f"{AS_OF}. Do not hand-edit. */\nwindow.TARA_REPLAY = "
        + json.dumps(payload, separators=(",", ":"))
        + ";\n",
        encoding="utf-8",
    )
    print(f"runs: {len(runs)}  verifies: {len(verifies)}  -> {out} ({out.stat().st_size/1024:.0f} KB)")


if __name__ == "__main__":
    main()
